-- programmers sql
-- print the cart_id bought both milk AND yogurt

SELECT C_MILK.CART_ID
FROM (SELECT CART_PRODUCTS.CART_ID, CART_PRODUCTS.NAME FROM CART_PRODUCTS
     WHERE NAME = 'MILK') AS C_MILK
INNER JOIN (SELECT CART_PRODUCTS.CART_ID, CART_PRODUCTS.NAME FROM CART_PRODUCTS
     WHERE NAME = 'YOGURT') AS C_YOGURT
ON C_MILK.CART_ID = C_YOGURT.CART_ID
GROUP BY C_MILK.CART_ID
ORDER BY CART_ID
