-- programmers sql
-- find the rental fee of cars available for a specific period of time

SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND((CAR.DAILY_FEE * 30) * (100 - DIS.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR

JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DIS
ON CAR.CAR_TYPE = DIS.CAR_TYPE
AND DIS.DURATION_TYPE = '30일 이상'
AND CAR.CAR_TYPE IN ('세단','SUV')

LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
ON CAR.CAR_ID = HIS.CAR_ID
AND HIS.END_DATE >= '2022-11-01' AND HIS.START_DATE <= '2022-11-30'
WHERE ((CAR.DAILY_FEE * 30) * (100 - DIS.DISCOUNT_RATE)/100) BETWEEN 500000 AND 1999999
AND HIS.CAR_ID IS NULL

ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC
