-- programmers sql
-- find the list of sales by author, and category

SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.AUTHOR_ID, CATEGORY
ORDER BY BOOK.AUTHOR_ID, CATEGORY DESC
